##rabbitmq
version: '3'

services:
  rabbitmq_tp2:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Management UI
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
